version: '3.8'

services:
  # Service 1 : La Base de données MySQL
  db:
    image: mysql:8.0
    container_name: healthcare-db
    restart: always
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Service 2 : Ton API Spring Boot
  api:
    build: .
    container_name: healthcare-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/healthcare_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=healthcare_user
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect

volumes:
  mysql_data: